MODEL_INPUTS = 160
NUMBER_OF_WAVLENGTHS = MODEL_INPUTS
WAVLENGTH_START = 0.4
WAVLENGTH_STOP = 1.2
MODEL_DISCRETE_OUTPUTS = 8
MODEL_CONTINUOUS_OUTPUTS = 10
MODEL_DISCRETE_PREDICTIONS = {
    "particle_material" : ["Au", "Al"],
    "hole" : ["holes", "no holes"]
    }

BATCH_SIZE = 128
EPOCHS = 80
